In [ ]:
#Q1

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


In [ ]:
# In the code above, type(list_[0]) is used to print the data type of the element in the list_,
# which is a string (<class 'str'>). array_list.dtype is used to print the data type of the elements
# in the array_list, which is <U1. The <U1 represents a Unicode string of length 1 in NumPy.

In [ ]:
#Q2

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in np.nditer(array_list):
    print(element.dtype)

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


In [ ]:
#Q3

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in np.nditer(array_list):
    print(element.dtype)

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
int64
int64
int64
int64
int64


In [ ]:
#Q4

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
#Q5

In [6]:
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
